### ISSUE TITLE
opencog-chatbot identifies the speech act but cannot reply

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2369]
Hello all,

I have given some knowledge and in turn asked some questions. Chatbot can identify the speech act but it cannot reply. It always says, "Sorry, I don't understand it".

This is the sample conversation which i made:
guile>  `(nlp-parse "Fred threw a red ball")` 
((SentenceNode "sentence@cb7790d6-21c9-481a-b230-1b38e6b7b9c1")
)
guile>   `(nlp-parse "John threw a green ball")`  
((SentenceNode "sentence@0a067710-7a9c-4c27-9d16-90193b907ef0")
)
guile>  `(nlp-parse "maria threw a blue rock")`  
((SentenceNode "sentence@4f6d027c-6a27-4f9f-8473-5862c0fc84f3")
)
guile>  `(process-query "priya" "who threw a red ball?")`  
Hello priya, you said: "who threw a red ball?"
You made an Interrogative SpeechAct
Sorry, I don't understand it
guile>  `(process-query "priya" "who threw a green ball?")`  
Hello priya, you said: "who threw a green ball?"
You made an Interrogative SpeechAct
Sorry, I don't understand it

What could be the problem?  what am i missing ? how can i fix this?

**Comment by leungmanhin** [comment]
https://github.com/opencog/opencog/pull/2370 should fix this problem

**Comment by vishnuu** [comment]
thanks for the reply

**Comment by linas** [comment]
Hi vishnuu, if the fix actually fixes your problem, then please close this issue.

**Comment by vishnuu** [comment]
No the fix does not solve the problem. i have modified the bot-api.scm as told in the fix. But still i am getting the same kind of reply.

**Comment by leungmanhin** [comment]
@vishnuu after you have modified the bot-api.scm (or would be better to pull the changes from master branch), please do `sudo make install` for opencog before retesting it

**Comment by vishnuu** [comment]
@leungmanhin Thanks for the reply.  Now it says "wrong-typ-arg" for all the qauestions which i ask.
Hello priya, you said: "who is ugly?"
You made an Interrogative SpeechAct
wrong-type-arg
(display Wrong type argument in position ~A: ~S (2 0) (0))
Sorry, I don't understand it
